export const ADD_TASK = 'ADD_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const TOGGLE_COMPLETION_STATUS = "TOGGLE_COMPLETION_STATUS";
export const FETCH_TASKS = "FETCH_TASKS";
export const DELETE_TASK = "DELETE_TASK";